# Generated by Django 3.1 on 2021-01-02 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Daily', '0002_todolist_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='owner',
        ),
        migrations.AddField(
            model_name='todolist',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
